---
- name: 'include os-specific vars'
  include_vars: "{{ansible_distribution | lower }}-{{ansible_distribution_major_version}}.yml"
  tags:
    - 'chrony'
    - 'chrony-vars'

- include: "install.yml"
- include: "configure.yml"
- include: "service.yml"
